services:
  oracle-db:
    image: gvenzl/oracle-free:23-slim-faststart
    container_name: product_rawmaterial_oracle
    environment:
      - ORACLE_PASSWORD=prm_pwd
      - APP_USER=user_prm
      - APP_USER_PASSWORD=12345678

    volumes:
      - oracle-data:/opt/oracle/oradata
    ports:
      - "1521:1521"
volumes:
  oracle-data: